# Generated by Django 5.0 on 2023-12-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pago.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pago.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desAFP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desRENTA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desISSS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default='2023-12-31 12:00')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pago.empleado')),
                ('mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pago.mes')),
            ],
        ),
    ]
